name: publish

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  HATCH_VERSION: "1.5.1"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Hatch
        run: pipx install hatch==$HATCH_VERSION

      - name: Build package
        run: hatch build -c

      - name: Upload distribution files
        uses: actions/upload-artifact@v3
        with:
          name: distribution-files
          path: dist/

      - name: Publish package on PyPI
        run: hatch publish -r main
        env:
          HATCH_INDEX_USER: ${{ secrets.HATCH_INDEX_USER }}
          HATCH_INDEX_AUTH: ${{ secrets.HATCH_INDEX_AUTH }}
